# Generated by Django 5.2 on 2025-05-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreeFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreeSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorts', to='tree.treefamily')),
            ],
            options={
                'ordering': ['name', 'family'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('planting_date', models.DateField(auto_now_add=True)),
                ('planting_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.place')),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='tree.treesort')),
            ],
            options={
                'ordering': ['name', 'sort__family', 'sort'],
            },
        ),
    ]
