# Generated by Django 5.2 on 2025-05-09 11:17

import django.db.models.deletion
import tree.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('year', models.IntegerField(choices=tree.models.year_choices, default=tree.models.current_year)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.tree')),
            ],
        ),
    ]
